<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Training Report</title>
    <style>
        @page {
            margin: 1.5cm;
            size: A4 landscape;
        }
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            margin: 0;
            padding: 0;
            background: #fff;
        }
        .ministry-header {
            text-align: center;
            padding: 20px 0;
            background: #fff;
            margin-bottom: 20px;
        }
        .ministry-header img {
            width: 100px;
            height: auto;
            margin-bottom: 15px;
        }
        .ministry-header h2 {
            color: #1a237e;
            margin: 5px 0;
            font-size: 20px;
            text-transform: uppercase;
            font-weight: bold;
            letter-spacing: 0.5px;
        }
        .ministry-header p {
            color: #1a237e;
            margin: 5px 0;
            font-size: 14px;
            letter-spacing: 0.3px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin: 25px 0;
            font-size: 12px;
            background: #fff;
            page-break-inside: avoid;
        }
        th {
            background: #f5f5f5;
            color: #1a237e;
            font-weight: 600;
            text-transform: uppercase;
            font-size: 11px;
            letter-spacing: 0.5px;
            padding: 12px 15px;
            text-align: left;
            border: 1px solid #e0e0e0;
        }
        td {
            padding: 12px 15px;
            color: #424242;
            font-weight: 400;
            border: 1px solid #e0e0e0;
        }
        .percentage {
            font-weight: 600;
            color: #2e7d32;
        }
        .total {
            font-weight: 600;
            color: #1a237e;
        }
        .footer {
            margin-top: 40px;
            text-align: center;
            font-size: 12px;
            color: #666;
            padding-top: 20px;
            border-top: 1px solid #e0e0e0;
        }
    </style>
</head>
<body>
    <div class="ministry-header">
        <img src="{{ public_path('asset/images/logo.png') }}" alt="Ministry Logo">
        <h2>Ministry of Education Science and Technology</h2>
        <p>United Republic of Tanzania</p>
        <p>Tanzania Teacher Portal</p>
    </div>

    <table>
        <thead>
            <tr>
                <th style="width: 25%;">Training Title</th>
                <th style="width: 25%;">Organization</th>
                <th style="width: 8%;">Male</th>
                <th style="width: 8%;">Female</th>
                <th style="width: 8%;">Total</th>
                <th style="width: 8%;">Attended</th>
                <th style="width: 8%;">Not Attended</th>
                <th style="width: 10%;">Attendance Rate</th>
            </tr>
        </thead>
        <tbody>
            @foreach($trainingDetails as $training)
            <tr>
                <td>{{ $training->title }}</td>
                <td>{{ $training->organization }}</td>
                <td>{{ $training->male_participants }}</td>
                <td>{{ $training->female_participants }}</td>
                <td class="total">{{ $training->male_participants + $training->female_participants }}</td>
                <td>{{ $training->attended }}</td>
                <td>{{ $training->not_attended }}</td>
                <td class="percentage">
                    {{ ($training->male_participants + $training->female_participants) > 0 
                        ? round(($training->attended / ($training->male_participants + $training->female_participants)) * 100, 1) . '%'
                        : '0%'
                    }}
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>This report was automatically generated by the Tanzania Teacher Portal</p>
        <p>Ministry of Education Science and Technology - United Republic of Tanzania</p>
    </div>
</body>
</html>
